/** Auto-generated by scripts/generate-apex-forums.mjs — edit the script and re-run. */
export type BlogSection = {
  heading: string
  body: string[]
}

export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  metaTitle: string
  metaDescription: string
  searchTerms: string
  date: string
  readMinutes: number
  tag: string
  sections: BlogSection[]
  howTo?: boolean
}

export const BLOGS: BlogPost[] = [
  {
    "slug": "features-list",
    "title": "Apex Legends Cheats Features",
    "excerpt": "Full module checklist for Apex Legends cheats on PC — aimbot, player ESP, loot & supply overlays, 2D radar, and config tools before you open checkout.",
    "metaTitle": "Apex Legends Cheats Features | Full Feature Overview",
    "metaDescription": "Full module checklist for Apex Legends cheats on PC — aimbot, player ESP, loot & supply overlays, 2D radar, and config tools before you open checkout.",
    "searchTerms": "Apex Legends cheat features, Apex Legends tools, Apex Legends features, Apex Legends cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Features",
    "sections": [
      {
        "heading": "What the menu includes",
        "body": [
          "This thread mirrors the live module list on apexhacks.org. Use it to compare aimbot, ESP, loot radar, and misc toggles against what you need in ring fights.",
          "Apex Legends trios and ranked lobbies reward fast looting and third-party timing — the module list focuses on player ESP, care package intel, death box highlights, and optional combat assist."
        ]
      },
      {
        "heading": "Aimbot, visuals, radar",
        "body": [
          "Aimbot options cover enable, FOV, smooth, bone selection, visible check, prediction, draw FOV, and draw target line.",
          "Player visuals include box, skeleton, head circle, health bar, distance, name, team/squad, weapon, view direction, OOF arrows, and max distance.",
          "Loot & world ESP, 2D radar markers, and misc no recoil / no spread / full bright / custom crosshair / config save-load round out the stack."
        ]
      }
    ]
  },
  {
    "slug": "complete-setup",
    "title": "Instructions to Use the Cheats",
    "excerpt": "Step-by-step Apex Legends cheat setup on Windows: confirm Active status, exclusions, load order, first ESP profile, optional aimbot, save config.",
    "metaTitle": "Instructions to Use the Cheats | Apex Legends Cheats Forum",
    "metaDescription": "Step-by-step Apex Legends cheat setup on Windows: confirm Active status, exclusions, load order, first ESP profile, optional aimbot, save config.",
    "searchTerms": "get apex legends cheats, get apex legends cheat, apex legends cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Setup",
    "sections": [
      {
        "heading": "1) Confirm status and checkout",
        "body": [
          "Open apexhacks.org and check Active on the product card. When Updating after a Apex Legends patch, wait — loading early wastes a session.",
          "Plans start from $35 monthly with lifetime options; use only the delivery link from your order email."
        ]
      },
      {
        "heading": "2) Windows prep",
        "body": [
          "Close Discord overlay, GeForce overlay, and RGB hooks. Add the delivery folder to Defender exclusions before first inject."
        ]
      },
      {
        "heading": "3) Load order",
        "body": [
          "Launch Apex Legends from Steam, reach the main menu, run the loader, open the menu, enable player ESP and radar, then add aimbot only if you want assist."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "aimbot-settings",
    "title": "Aimbot Settings: What Level & Why Won’t I Get Banned?",
    "excerpt": "Tune Apex Legends aimbot FOV, smooth, and visible check so tracking helps in ring fights without obvious kill-cam clips.",
    "metaTitle": "Aimbot Settings: What Level & Why Won’t I Get Banned? | Apex Legends Cheats Forum",
    "metaDescription": "Tune Apex Legends aimbot FOV, smooth, and visible check so tracking helps in ring fights without obvious kill-cam clips.",
    "searchTerms": "apex legends aimbot, buy apex legends aimbot, apex legends aimbot lifetime",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Start conservative",
        "body": [
          "Wide FOV and zero smooth get reported fast — players review deaths in a 60-player lobby. Start small FOV, higher smooth, body bones first.",
          "Visible check stops tracking through solid cover; keep it on unless you accept more reports."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "esp-wallhack-guide",
    "title": "Player ESP Settings: What to Enable First",
    "excerpt": "Configure Apex Legends player ESP — box, skeleton, distance, weapon, team filter — without cluttering your HUD in mountain fights.",
    "metaTitle": "Player ESP Settings: What to Enable First | Apex Legends Cheats Forum",
    "metaDescription": "Configure Apex Legends player ESP — box, skeleton, distance, weapon, team filter — without cluttering your HUD in mountain fights.",
    "searchTerms": "apex legends esp, buy apex legends esp, apex legends esp lifetime",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Recommended first toggles",
        "body": [
          "Enable box, distance, and name. Add weapon ESP when you rotate solo — DMR vs SMG changes peek timing at 40m.",
          "Cap max distance around 150–200m so tags stay readable during ring pushes."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "loot-esp-first",
    "title": "Loot ESP Settings: What to Enable First",
    "excerpt": "Death box, care package, and tier highlights for Apex Legends — loot faster after kills without guessing.",
    "metaTitle": "Loot ESP Settings: What to Enable First | Apex Legends Cheats Forum",
    "metaDescription": "Death box, care package, and tier highlights for Apex Legends — loot faster after kills without guessing.",
    "searchTerms": "apex legends esp",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Loot ESP",
    "sections": [
      {
        "heading": "Priority toggles",
        "body": [
          "Enable death box ESP and care package markers first. Cap ground-loot distance around 80m so your HUD stays readable in endgame.",
          "Pair with squad markers on 2D radar when your team splits — one player can still see package pulls on the minimap."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "radar-recommended-config",
    "title": "2D Radar & Ring Rotations: Recommended Configurations",
    "excerpt": "2D radar range, player markers, and ring timer overlay tuned for Apex Legends rotations and third-party audio.",
    "metaTitle": "2D Radar & Ring Rotations: Recommended Configurations | Apex Legends Cheats Forum",
    "metaDescription": "2D radar range, player markers, and ring timer overlay tuned for Apex Legends rotations and third-party audio.",
    "searchTerms": "apex legends esp",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Radar defaults",
        "body": [
          "Start radar range medium — too wide floods the minimap in dense fights. Player markers on; tighten range when the ring closes.",
          "Drop range when pushing buildings so arrows match audible footsteps."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "combat-assist-settings",
    "title": "Combat Assist Settings: What Level & Ban Risk Explained",
    "excerpt": "Balance aimbot smooth, FOV, and ESP noise for Apex Legends ranked-style queues — report habits and kill cam reality.",
    "metaTitle": "Combat Assist Settings: What Level & Ban Risk Explained | Apex Legends Cheats Forum",
    "metaDescription": "Balance aimbot smooth, FOV, and ESP noise for Apex Legends ranked-style queues — report habits and kill cam reality.",
    "searchTerms": "apex legends aimbot",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Combat",
    "sections": [
      {
        "heading": "Reports matter",
        "body": [
          "Players flag snap deaths and impossible prefires. ESP-only nights plus low smooth aimbot beat max settings in week one."
        ]
      }
    ]
  },
  {
    "slug": "game-patch-status",
    "title": "Apex Legends Cheats After a Game Patch — What to Do",
    "excerpt": "What Active vs Updating means after Apex Legends patches — and why loading early wastes your ring session.",
    "metaTitle": "Apex Legends Cheats After a Game Patch — What to Do | Apex Legends Cheats Forum",
    "metaDescription": "What Active vs Updating means after Apex Legends patches — and why loading early wastes your ring session.",
    "searchTerms": "apex legends cheats, apex legends anti-cheat",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Status",
    "sections": [
      {
        "heading": "Status labels",
        "body": [
          "Active means the loader matches the live client. Updating means wait — check apexhacks.org before every session."
        ]
      }
    ]
  },
  {
    "slug": "ultimate-apex-legends-cheats-guide",
    "title": "Ultimate Apex Legends Cheats Guide: Setup & Features",
    "excerpt": "Overview of Apex Legends cheat modules, loader status, and first-night config for ranked trios on PC.",
    "metaTitle": "Ultimate Apex Legends Cheats Guide: Setup & Features | Apex Legends Cheats Forum",
    "metaDescription": "Overview of Apex Legends cheat modules, loader status, and first-night config for ranked trios on PC.",
    "searchTerms": "apex legends cheats, apex legends esp, apex legends aimbot, apex legends anti-cheat",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Guide",
    "sections": [
      {
        "heading": "Feature map",
        "body": [
          "Aimbot, player ESP, loot & supply ESP, 2D radar, and misc weapon helpers — match toggles to how your trio rotates zones."
        ]
      }
    ]
  },
  {
    "slug": "buy-apex-legends-cheats-safely",
    "title": "Where to Buy Apex Legends Cheats Safely: Full Access Options",
    "excerpt": "How to buy Apex Legends cheats with clear pricing, digital delivery, and status labels before you load into a 60-player lobby.",
    "metaTitle": "Where to Buy Apex Legends Cheats Safely: Full Access Options | Apex Legends Cheats Forum",
    "metaDescription": "How to buy Apex Legends cheats with clear pricing, digital delivery, and status labels before you load into a 60-player lobby.",
    "searchTerms": "buy apex legends cheats, buy apex legends cheat, buy apex legends esp, buy apex legends aimbot",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Buying",
    "sections": [
      {
        "heading": "Before checkout",
        "body": [
          "Use apexhacks.org for live Active/Updating status. Monthly and lifetime licenses include loader updates when status allows."
        ]
      }
    ]
  },
  {
    "slug": "apex-legends-cheats-lifetime",
    "title": "Apex Legends Cheats Lifetime License: Is Permanent Access Worth It?",
    "excerpt": "Lifetime vs monthly Apex Legends cheat access — when permanent makes sense for regular ring players.",
    "metaTitle": "Apex Legends Cheats Lifetime License: Is Permanent Access Worth It? | Apex Legends Cheats Forum",
    "metaDescription": "Lifetime vs monthly Apex Legends cheat access — when permanent makes sense for regular ring players.",
    "searchTerms": "apex legends cheats lifetime, apex legends cheat lifetime, apex legends aimbot lifetime, apex legends esp lifetime",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Pricing",
    "sections": [
      {
        "heading": "Who lifetime fits",
        "body": [
          "If you play multiple nights per week through seasons, lifetime offsets monthly renewals. Casual players often start monthly first."
        ]
      }
    ]
  },
  {
    "slug": "apex-legends-cheat-discord",
    "title": "Official Apex Legends Cheat Discord Server: How to Join for Live Support",
    "excerpt": "Find live Apex Legends cheat support channels after purchase — status pings, config screenshots, and patch-day threads.",
    "metaTitle": "Official Apex Legends Cheat Discord Server: How to Join for Live Support | Apex Legends Cheats Forum",
    "metaDescription": "Find live Apex Legends cheat support channels after purchase — status pings, config screenshots, and patch-day threads.",
    "searchTerms": "apex legends cheat discord",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Community",
    "sections": [
      {
        "heading": "What Discord is for",
        "body": [
          "Discord complements the forums here — quick loader screenshots and patch chatter. Purchase still flows through the store link on the product page."
        ]
      }
    ]
  },
  {
    "slug": "best-apex-legends-cheats-review-2026",
    "title": "Best Apex Legends Cheats Review & Comparison 2026: Features, Safety & Value",
    "excerpt": "2026 Apex Legends cheat comparison — ESP clarity, aimbot tuning, loot radar, pricing, and loader maintenance habits.",
    "metaTitle": "Best Apex Legends Cheats Review & Comparison 2026: Features, Safety & Value | Apex Legends Cheats Forum",
    "metaDescription": "2026 Apex Legends cheat comparison — ESP clarity, aimbot tuning, loot radar, pricing, and loader maintenance habits.",
    "searchTerms": "apex legends cheats, buy apex legends cheats, apex legends cheats lifetime",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Review",
    "sections": [
      {
        "heading": "What we compared",
        "body": [
          "Module depth, config save/load, status transparency, and how fast ESP recovered after game patches — not hype claims."
        ]
      }
    ]
  },
  {
    "slug": "hwid-spoofer-safety",
    "title": "Discover What an HWID Spoofer Does for Safety",
    "excerpt": "HWID spoofer basics for PC gamers — what hardware IDs are, why some players research them, and realistic limits.",
    "metaTitle": "Discover What an HWID Spoofer Does for Safety | Apex Legends Cheats Forum",
    "metaDescription": "HWID spoofer basics for PC gamers — what hardware IDs are, why some players research them, and realistic limits.",
    "searchTerms": "apex legends anti-cheat",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Safety",
    "sections": [
      {
        "heading": "Plain-language overview",
        "body": [
          "A spoofer changes how your PC fingerprint appears to some anti-cheat stacks. It is not a substitute for reading loader status or playing conservatively."
        ]
      }
    ]
  },
  {
    "slug": "apex-legends-aimbot-options",
    "title": "Precision Target Lock: Mastering Apex Legends Aimbot Options",
    "excerpt": "Deep dive on Apex Legends aimbot enable, FOV, smooth, bones, visible check, and prediction.",
    "metaTitle": "Precision Target Lock: Mastering Apex Legends Aimbot Options | Apex Legends Cheats Forum",
    "metaDescription": "Deep dive on Apex Legends aimbot enable, FOV, smooth, bones, visible check, and prediction.",
    "searchTerms": "apex legends aimbot",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Core toggles",
        "body": [
          "Work FOV down before touching prediction — leading targets matters most on sliding and zipline fights."
        ]
      }
    ]
  },
  {
    "slug": "enable-aimbot-safely",
    "title": "How to Configure and Enable Aimbot Safely in Apex Legends",
    "excerpt": "Enable aimbot only after ESP and radar baselines — bind toggles and test in offline range first.",
    "metaTitle": "How to Configure and Enable Aimbot Safely in Apex Legends | Apex Legends Cheats Forum",
    "metaDescription": "Enable aimbot only after ESP and radar baselines — bind toggles and test in offline range first.",
    "searchTerms": "apex legends aimbot",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Enable order",
        "body": [
          "Player ESP on, visible check on, then enable aimbot with high smooth."
        ]
      }
    ]
  },
  {
    "slug": "aimbot-fov-settings",
    "title": "Dialing in Your Field of View Settings for Natural Aiming",
    "excerpt": "FOV cone sizing for CQB buildings vs open hills in Apex Legends.",
    "metaTitle": "Dialing in Your Field of View Settings for Natural Aiming | Apex Legends Cheats Forum",
    "metaDescription": "FOV cone sizing for CQB buildings vs open hills in Apex Legends.",
    "searchTerms": "Apex Legends Aimbot, aimbot fov settings, Apex Legends cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "FOV tips",
        "body": [
          "Draw FOV helps you see the cone — keep it smaller than your reflex FOV."
        ]
      }
    ]
  },
  {
    "slug": "aimbot-smooth-guide",
    "title": "How Smooth Aiming Keeps Your Gameplay Looking Legitimate",
    "excerpt": "Smooth values that reduce snap on kill cams without feeling sluggish.",
    "metaTitle": "How Smooth Aiming Keeps Your Gameplay Looking Legitimate | Apex Legends Cheats Forum",
    "metaDescription": "Smooth values that reduce snap on kill cams without feeling sluggish.",
    "searchTerms": "Apex Legends Aimbot, aimbot smooth guide, Apex Legends cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Smoothing",
        "body": [
          "Higher smooth on DMR, moderate on AR — save profiles per weapon class."
        ]
      }
    ]
  },
  {
    "slug": "bone-selection-guide",
    "title": "Targeted Bone Selection Guide: Headshots vs Body Shots",
    "excerpt": "Bone selection tradeoffs for moving targets and armored foes.",
    "metaTitle": "Targeted Bone Selection Guide: Headshots vs Body Shots | Apex Legends Cheats Forum",
    "metaDescription": "Bone selection tradeoffs for moving targets and armored foes.",
    "searchTerms": "Apex Legends Aimbot, bone selection guide, Apex Legends cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Bones",
        "body": [
          "Chest default for moving tags; head bone only when smooth is high enough."
        ]
      }
    ]
  },
  {
    "slug": "visible-check-guide",
    "title": "Preventing Wall Tracking: Why Visible Check Is Essential",
    "excerpt": "Visible check stops locks through metal walls — use it in urban rings.",
    "metaTitle": "Preventing Wall Tracking: Why Visible Check Is Essential | Apex Legends Cheats Forum",
    "metaDescription": "Visible check stops locks through metal walls — use it in urban rings.",
    "searchTerms": "Apex Legends Aimbot, visible check guide, Apex Legends cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Visible check",
        "body": [
          "Without it, kill cams show pre-fire through cover — reports stack fast."
        ]
      }
    ]
  },
  {
    "slug": "bullet-prediction",
    "title": "Leading Your Shots: Bullet Prediction Mechanics Explained",
    "excerpt": "Prediction for sprinting targets and zipline fights in Apex Legends.",
    "metaTitle": "Leading Your Shots: Bullet Prediction Mechanics Explained | Apex Legends Cheats Forum",
    "metaDescription": "Prediction for sprinting targets and zipline fights in Apex Legends.",
    "searchTerms": "Apex Legends Aimbot, bullet prediction, Apex Legends cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Prediction",
        "body": [
          "Tune after FOV/smooth — prediction magnifies mistakes if base aim is too aggressive."
        ]
      }
    ]
  },
  {
    "slug": "draw-fov-overlays",
    "title": "Visualizing Your Aim Radius: How to Use Draw FOV Overlays",
    "excerpt": "Draw FOV circle usage without blocking center crosshair vision.",
    "metaTitle": "Visualizing Your Aim Radius: How to Use Draw FOV Overlays | Apex Legends Cheats Forum",
    "metaDescription": "Draw FOV circle usage without blocking center crosshair vision.",
    "searchTerms": "Apex Legends Aimbot, draw fov overlays, Apex Legends cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Draw FOV",
        "body": [
          "Thin white circle matches most HUDs — disable for clips if teammates watch."
        ]
      }
    ]
  },
  {
    "slug": "draw-target-line",
    "title": "Target Line Visuals: Instantly Identify Locked Enemies",
    "excerpt": "Target line overlays show which tag aimbot selected in crowded fights.",
    "metaTitle": "Target Line Visuals: Instantly Identify Locked Enemies | Apex Legends Cheats Forum",
    "metaDescription": "Target line overlays show which tag aimbot selected in crowded fights.",
    "searchTerms": "Apex Legends Aimbot, draw target line, Apex Legends cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Target line",
        "body": [
          "Helpful in trios when three tags stack — turn off for solo stealth play."
        ]
      }
    ]
  },
  {
    "slug": "player-visuals-breakdown",
    "title": "Complete Player Visuals Breakdown for Tactical Dominance",
    "excerpt": "Every player visual toggle explained for Apex Legends three-team lobbies.",
    "metaTitle": "Complete Player Visuals Breakdown for Tactical Dominance | Apex Legends Cheats Forum",
    "metaDescription": "Every player visual toggle explained for Apex Legends three-team lobbies.",
    "searchTerms": "apex legends esp, buy apex legends esp, apex legends esp lifetime",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Player visuals",
        "body": [
          "Mix box + skeleton sparingly — pick one primary outline to reduce noise."
        ]
      }
    ]
  },
  {
    "slug": "box-esp-setup",
    "title": "Box ESP Setup: 2D vs 3D Bounding Boxes for Target Tracking",
    "excerpt": "Box ESP styles for long-range hill fights vs close building clears.",
    "metaTitle": "Box ESP Setup: 2D vs 3D Bounding Boxes for Target Tracking | Apex Legends Cheats Forum",
    "metaDescription": "Box ESP styles for long-range hill fights vs close building clears.",
    "searchTerms": "apex legends esp",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Boxes",
        "body": [
          "2D boxes read faster at distance; 3D helps when targets sit on stairs."
        ]
      }
    ]
  },
  {
    "slug": "skeleton-esp-guide",
    "title": "Skeleton ESP: Real-Time Stance and Movement Overlay Guide",
    "excerpt": "Skeleton overlays show crouch vs standing through windows before you push.",
    "metaTitle": "Skeleton ESP: Real-Time Stance and Movement Overlay Guide | Apex Legends Cheats Forum",
    "metaDescription": "Skeleton overlays show crouch vs standing through windows before you push.",
    "searchTerms": "apex legends esp",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Skeleton",
        "body": [
          "Mute skeleton color — neon green reads obvious on recordings."
        ]
      }
    ]
  },
  {
    "slug": "head-circle-visuals",
    "title": "Head Circle Visuals: Instant Headshot Alignment Overlays",
    "excerpt": "Head circle pairing with low smooth aimbot for DMR players.",
    "metaTitle": "Head Circle Visuals: Instant Headshot Alignment Overlays | Apex Legends Cheats Forum",
    "metaDescription": "Head circle pairing with low smooth aimbot for DMR players.",
    "searchTerms": "Apex Legends ESP, head circle visuals, Apex Legends cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Head circle",
        "body": [
          "Combine with visible check so you only pre-aim visible peeks."
        ]
      }
    ]
  },
  {
    "slug": "health-bar-tracking",
    "title": "Enemy Health Bar Tracking: Prioritize Low-HP Targets",
    "excerpt": "Health bars help focus fire in squad wipes during endgame fights.",
    "metaTitle": "Enemy Health Bar Tracking: Prioritize Low-HP Targets | Apex Legends Cheats Forum",
    "metaDescription": "Health bars help focus fire in squad wipes during endgame fights.",
    "searchTerms": "Apex Legends ESP, health bar tracking, Apex Legends cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Health bars",
        "body": [
          "Vertical bars beside boxes — disable on max distance tags to save clutter."
        ]
      }
    ]
  },
  {
    "slug": "distance-esp-indicators",
    "title": "Distance ESP Indicators: Judging Combat Ranges Effectively",
    "excerpt": "Distance readouts for picking SMG vs DMR engagements on roads.",
    "metaTitle": "Distance ESP Indicators: Judging Combat Ranges Effectively | Apex Legends Cheats Forum",
    "metaDescription": "Distance readouts for picking SMG vs DMR engagements on roads.",
    "searchTerms": "Apex Legends ESP, distance esp indicators, Apex Legends cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Distance",
        "body": [
          "Sort mentally: under 30m push, 30–80m hold angle, 80m+ mark for squad."
        ]
      }
    ]
  },
  {
    "slug": "player-name-tags",
    "title": "Player Name Tags: Identifying High-Value Targets In-Game",
    "excerpt": "Name ESP for remembering repeat third parties in long sessions.",
    "metaTitle": "Player Name Tags: Identifying High-Value Targets In-Game | Apex Legends Cheats Forum",
    "metaDescription": "Name ESP for remembering repeat third parties in long sessions.",
    "searchTerms": "Apex Legends ESP, player name tags, Apex Legends cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Names",
        "body": [
          "Screenshot names only in Discord DMs — avoid public callouts."
        ]
      }
    ]
  },
  {
    "slug": "team-squad-filtering",
    "title": "Team & Squad Visual Filtering: Avoid Screen Clutter",
    "excerpt": "Team/squad filters so friendly markers do not mask enemies.",
    "metaTitle": "Team & Squad Visual Filtering: Avoid Screen Clutter | Apex Legends Cheats Forum",
    "metaDescription": "Team/squad filters so friendly markers do not mask enemies.",
    "searchTerms": "Apex Legends ESP, team squad filtering, Apex Legends cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Team filter",
        "body": [
          "Color allies blue, enemies red — verify squad IDs after matchmaking."
        ]
      }
    ]
  },
  {
    "slug": "enemy-weapon-esp",
    "title": "Enemy Weapon ESP: Spotting High-Tier Guns Instantly",
    "excerpt": "Weapon ESP tells you when a tag carries a DMR worth pushing or avoiding.",
    "metaTitle": "Enemy Weapon ESP: Spotting High-Tier Guns Instantly | Apex Legends Cheats Forum",
    "metaDescription": "Weapon ESP tells you when a tag carries a DMR worth pushing or avoiding.",
    "searchTerms": "Apex Legends ESP, enemy weapon esp, Apex Legends cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Weapon ESP",
        "body": [
          "Pair with distance — SMG at 90m is often a wounded player, not a bait."
        ]
      }
    ]
  },
  {
    "slug": "view-direction-lines",
    "title": "View Direction Lines: Spotting Enemy Flanks Before They Happen",
    "excerpt": "View direction lines show where a tag is looking — flank safely.",
    "metaTitle": "View Direction Lines: Spotting Enemy Flanks Before They Happen | Apex Legends Cheats Forum",
    "metaDescription": "View direction lines show where a tag is looking — flank safely.",
    "searchTerms": "Apex Legends ESP, view direction lines, Apex Legends cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "ESP",
    "sections": [
      {
        "heading": "View lines",
        "body": [
          "Disable on max clutter maps; keep for solo flanks on open hills."
        ]
      }
    ]
  },
  {
    "slug": "oof-arrows-guide",
    "title": "Out of Field Arrows: Off-Screen Threat Alerts Explained",
    "excerpt": "OOF arrows for sound-only contacts during ring rotates.",
    "metaTitle": "Out of Field Arrows: Off-Screen Threat Alerts Explained | Apex Legends Cheats Forum",
    "metaDescription": "OOF arrows for sound-only contacts during ring rotates.",
    "searchTerms": "Apex Legends ESP, oof arrows guide, Apex Legends cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "OOF arrows",
        "body": [
          "Combine with radar — arrow color matches threat bearing."
        ]
      }
    ]
  },
  {
    "slug": "max-distance-filters",
    "title": "Optimizing Max Distance Filters to Clean Up Your Screen",
    "excerpt": "Max distance caps for 60-player lobbies without losing close threats.",
    "metaTitle": "Optimizing Max Distance Filters to Clean Up Your Screen | Apex Legends Cheats Forum",
    "metaDescription": "Max distance caps for 60-player lobbies without losing close threats.",
    "searchTerms": "Apex Legends ESP, max distance filters, Apex Legends cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Max distance",
        "body": [
          "150m baseline; drop to 100m in final circle style fights."
        ]
      }
    ]
  },
  {
    "slug": "death-box-esp-guide",
    "title": "Death Box ESP: Spot Resboxes After Team Fights",
    "excerpt": "Death box ESP tuning — colors, max distance, and when to hide distant boxes during endgame.",
    "metaTitle": "Death Box ESP: Spot Resboxes After Team Fights | Apex Legends Cheats Forum",
    "metaDescription": "Death box ESP tuning — colors, max distance, and when to hide distant boxes during endgame.",
    "searchTerms": "apex legends esp",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Loot ESP",
    "sections": [
      {
        "heading": "Death box overlays",
        "body": [
          "Use a distinct color for death boxes vs care packages so you do not third-party the wrong fight.",
          "Past ring 4, drop death box distance to ~60m so only nearby swaps show during chaos."
        ]
      }
    ]
  },
  {
    "slug": "care-package-tracking",
    "title": "Care Package Tracking: Contest High-Tier Drops Safely",
    "excerpt": "Track care package landings and contest timing across ring rotations.",
    "metaTitle": "Care Package Tracking: Contest High-Tier Drops Safely | Apex Legends Cheats Forum",
    "metaDescription": "Track care package landings and contest timing across ring rotations.",
    "searchTerms": "apex legends esp",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Loot ESP",
    "sections": [
      {
        "heading": "Tracking",
        "body": [
          "Mark packages on radar and ESP — dual cue prevents walking into a full squad on armor."
        ]
      }
    ]
  },
  {
    "slug": "loot-tier-highlights",
    "title": "Loot Tier Highlights: Purple Armor and Attachments",
    "excerpt": "Tier colors distinguish purple armor, gold knockdown shields, and attachment tiers.",
    "metaTitle": "Loot Tier Highlights: Purple Armor and Attachments | Apex Legends Cheats Forum",
    "metaDescription": "Tier colors distinguish purple armor, gold knockdown shields, and attachment tiers.",
    "searchTerms": "Apex Legends Loot ESP, loot tier highlights, Apex Legends cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Loot ESP",
    "sections": [
      {
        "heading": "Types",
        "body": [
          "Do not sprint blindly on purple tags — confirm with player ESP before you commit."
        ]
      }
    ]
  },
  {
    "slug": "loot-max-distance",
    "title": "Loot Max Distance: Keep Your HUD Clean",
    "excerpt": "Distance filters for ground loot and death boxes in stacked lobbies.",
    "metaTitle": "Loot Max Distance: Keep Your HUD Clean | Apex Legends Cheats Forum",
    "metaDescription": "Distance filters for ground loot and death boxes in stacked lobbies.",
    "searchTerms": "Apex Legends Loot ESP, loot max distance, Apex Legends cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Loot ESP",
    "sections": [
      {
        "heading": "Distance",
        "body": [
          "Hide ground loot beyond 50m in final rings if you only care about immediate swaps."
        ]
      }
    ]
  },
  {
    "slug": "shield-helmet-highlight",
    "title": "Shield and Helmet ESP: Swap Armor Faster",
    "excerpt": "Helmet and shield highlights — spot upgrade swaps without opening every bin.",
    "metaTitle": "Shield and Helmet ESP: Swap Armor Faster | Apex Legends Cheats Forum",
    "metaDescription": "Helmet and shield highlights — spot upgrade swaps without opening every bin.",
    "searchTerms": "Apex Legends Loot ESP, shield helmet highlight, Apex Legends cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Loot ESP",
    "sections": [
      {
        "heading": "Armor highlights",
        "body": [
          "Slow peek care packages — teams often hold nearby cover."
        ]
      }
    ]
  },
  {
    "slug": "radar-options-guide",
    "title": "2D Radar Options: Complete Minimap Awareness Guide",
    "excerpt": "Radar module overview for Apex Legends minimap power users.",
    "metaTitle": "2D Radar Options: Complete Minimap Awareness Guide | Apex Legends Cheats Forum",
    "metaDescription": "Radar module overview for Apex Legends minimap power users.",
    "searchTerms": "Apex Legends Radar, radar options guide, Apex Legends cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Radar options",
        "body": [
          "Player markers plus ring timer — toggle loot ESP off in final 1v1s if the HUD feels busy."
        ]
      }
    ]
  },
  {
    "slug": "custom-2d-radar-hud",
    "title": "Positioning Mastery: Setting Up a Custom 2D Radar HUD",
    "excerpt": "Radar size and corner placement on ultrawide vs 1080p.",
    "metaTitle": "Positioning Mastery: Setting Up a Custom 2D Radar HUD | Apex Legends Cheats Forum",
    "metaDescription": "Radar size and corner placement on ultrawide vs 1080p.",
    "searchTerms": "Apex Legends Radar, custom 2d radar hud, Apex Legends cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Radar",
    "sections": [
      {
        "heading": "HUD placement",
        "body": [
          "Bottom-left stack above native minimap — avoid covering ring countdown UI."
        ]
      }
    ]
  },
  {
    "slug": "player-markers-radar",
    "title": "Player Markers on Radar: Tracking Enemy Rotation Paths",
    "excerpt": "Read rotation arcs on 2D radar before third party sound.",
    "metaTitle": "Player Markers on Radar: Tracking Enemy Rotation Paths | Apex Legends Cheats Forum",
    "metaDescription": "Read rotation arcs on 2D radar before third party sound.",
    "searchTerms": "Apex Legends Radar, player markers radar, Apex Legends cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Player markers",
        "body": [
          "Watch marker velocity — sprinting tags toward ring = rotate early."
        ]
      }
    ]
  },
  {
    "slug": "ring-timer-radar",
    "title": "Ring Timer on Radar: Rotate Before the Zone Closes",
    "excerpt": "Ring timer overlay on radar — rotate before third parties catch you looting.",
    "metaTitle": "Ring Timer on Radar: Rotate Before the Zone Closes | Apex Legends Cheats Forum",
    "metaDescription": "Ring timer overlay on radar — rotate before third parties catch you looting.",
    "searchTerms": "Apex Legends Radar, ring timer radar, Apex Legends cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Ring timer",
        "body": [
          "Pair with player ESP — a quiet package lane can still have teams holding ridge."
        ]
      }
    ]
  },
  {
    "slug": "radar-range-calibration",
    "title": "Calibrating Radar Range for Close and Long-Range Fights",
    "excerpt": "Radar range tuning for urban vs mountain maps.",
    "metaTitle": "Calibrating Radar Range for Close and Long-Range Fights | Apex Legends Cheats Forum",
    "metaDescription": "Radar range tuning for urban vs mountain maps.",
    "searchTerms": "Apex Legends Radar, radar range calibration, Apex Legends cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Range",
        "body": [
          "Short range in towns; widen when holding open hills between zones."
        ]
      }
    ]
  },
  {
    "slug": "misc-utility-features",
    "title": "Miscellaneous Utility Features for Ultimate Gameplay Control",
    "excerpt": "Misc menu: recoil, spread, brightness, crosshair, configs.",
    "metaTitle": "Miscellaneous Utility Features for Ultimate Gameplay Control | Apex Legends Cheats Forum",
    "metaDescription": "Misc menu: recoil, spread, brightness, crosshair, configs.",
    "searchTerms": "Apex Legends Misc, misc utility features, Apex Legends cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Misc stack",
        "body": [
          "No recoil/no spread are loud on spectator cams — use sparingly in public lobbies."
        ]
      }
    ]
  },
  {
    "slug": "no-recoil-compensation",
    "title": "Zero Recoil Compensation: Eliminating Weapon Kickback",
    "excerpt": "No recoil toggle habits for burst weapons in Apex Legends.",
    "metaTitle": "Zero Recoil Compensation: Eliminating Weapon Kickback | Apex Legends Cheats Forum",
    "metaDescription": "No recoil toggle habits for burst weapons in Apex Legends.",
    "searchTerms": "Apex Legends Misc, no recoil compensation, Apex Legends cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Misc",
    "sections": [
      {
        "heading": "No recoil",
        "body": [
          "Tap fire still looks cleaner than full auto laser beams."
        ]
      }
    ]
  },
  {
    "slug": "no-spread-elimination",
    "title": "Perfect Bullet Spread Elimination: Laser-Accurate Firing",
    "excerpt": "No spread interaction with movement and jump shots.",
    "metaTitle": "Perfect Bullet Spread Elimination: Laser-Accurate Firing | Apex Legends Cheats Forum",
    "metaDescription": "No spread interaction with movement and jump shots.",
    "searchTerms": "Apex Legends Misc, no spread elimination, Apex Legends cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Misc",
    "sections": [
      {
        "heading": "No spread",
        "body": [
          "Combine with moderate aimbot — max stack screams on kill cam."
        ]
      }
    ]
  },
  {
    "slug": "full-bright-toggles",
    "title": "Full Bright Visual Toggles: Max Visibility in Dark Map Areas",
    "excerpt": "Full bright for interior clears without cranking gamma globally.",
    "metaTitle": "Full Bright Visual Toggles: Max Visibility in Dark Map Areas | Apex Legends Cheats Forum",
    "metaDescription": "Full bright for interior clears without cranking gamma globally.",
    "searchTerms": "Apex Legends Misc, full bright toggles, Apex Legends cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Full bright",
        "body": [
          "Toggle off for screenshots — flat lighting looks unnatural in clips."
        ]
      }
    ]
  },
  {
    "slug": "custom-crosshair-overlays",
    "title": "Custom Crosshair Overlays for Hipfire and Precision Shooting",
    "excerpt": "Custom crosshair when iron sights clutter the screen.",
    "metaTitle": "Custom Crosshair Overlays for Hipfire and Precision Shooting | Apex Legends Cheats Forum",
    "metaDescription": "Custom crosshair when iron sights clutter the screen.",
    "searchTerms": "Apex Legends Misc, custom crosshair overlays, Apex Legends cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Crosshair",
        "body": [
          "Small dot for hipfire, circle for DMR — match native sight color."
        ]
      }
    ]
  },
  {
    "slug": "config-save-load",
    "title": "Fast Setup: How to Save and Load Your Custom Config Settings",
    "excerpt": "Config profiles for solo vs trio ring nights.",
    "metaTitle": "Fast Setup: How to Save and Load Your Custom Config Settings | Apex Legends Cheats Forum",
    "metaDescription": "Config profiles for solo vs trio ring nights.",
    "searchTerms": "Apex Legends Misc, config save load, Apex Legends cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Configs",
        "body": [
          "Save \"esp-only\", \"loot\", and \"full assist\" — load before queue."
        ]
      }
    ]
  },
  {
    "slug": "windows-setup",
    "title": "Apex Legends Cheats on Windows 10 and 11",
    "excerpt": "Windows prep for Apex Legends cheats — overlays, Defender, TPM/HVCI notes.",
    "metaTitle": "Apex Legends Cheats on Windows 10 and 11 | Apex Legends Cheats Forum",
    "metaDescription": "Windows prep for Apex Legends cheats — overlays, Defender, TPM/HVCI notes.",
    "searchTerms": "Apex Legends Windows, windows setup, Apex Legends cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Windows",
    "sections": [
      {
        "heading": "Supported systems",
        "body": [
          "Windows 10/11 with Steam Apex Legends — close overlays before inject."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "disable-antivirus",
    "title": "Antivirus Exclusions for Apex Legends Cheats",
    "excerpt": "Allowlist loaders in Defender so files are not quarantined mid-setup.",
    "metaTitle": "Antivirus Exclusions for Apex Legends Cheats | Apex Legends Cheats Forum",
    "metaDescription": "Allowlist loaders in Defender so files are not quarantined mid-setup.",
    "searchTerms": "Apex Legends Antivirus, disable antivirus, Apex Legends cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Antivirus",
    "sections": [
      {
        "heading": "Defender",
        "body": [
          "Folder exclusion before first run — restore quarantines if you retried blindly."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "hotkeys",
    "title": "Apex Legends Cheat Hotkeys After Load",
    "excerpt": "Menu and toggle hotkeys — ESP, aimbot, radar panic binds.",
    "metaTitle": "Apex Legends Cheat Hotkeys After Load | Apex Legends Cheats Forum",
    "metaDescription": "Menu and toggle hotkeys — ESP, aimbot, radar panic binds.",
    "searchTerms": "Apex Legends Hotkeys, hotkeys, Apex Legends cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Hotkeys",
    "sections": [
      {
        "heading": "Suggested binds",
        "body": [
          "Menu toggle, ESP master, aimbot toggle, radar toggle — write them down once."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "loader-errors",
    "title": "Fix Apex Legends Cheat Loader Errors",
    "excerpt": "Menu not opening, instant close, antivirus quarantine, failed inject.",
    "metaTitle": "Fix Apex Legends Cheat Loader Errors | Apex Legends Cheats Forum",
    "metaDescription": "Menu not opening, instant close, antivirus quarantine, failed inject.",
    "searchTerms": "Apex Legends Support, loader errors, Apex Legends cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Support",
    "sections": [
      {
        "heading": "Check status first",
        "body": [
          "Updating builds fail for reasons settings cannot fix — confirm Active."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "load-status-checklist",
    "title": "Pre-Load Checklist Before You Buy or Queue",
    "excerpt": "Confirm Active status, game version, and config before ranked-style queues.",
    "metaTitle": "Pre-Load Checklist Before You Buy or Queue | Apex Legends Cheats Forum",
    "metaDescription": "Confirm Active status, game version, and config before ranked-style queues.",
    "searchTerms": "Apex Legends Status, load status checklist, Apex Legends cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Status",
    "sections": [
      {
        "heading": "Before checkout",
        "body": [
          "Confirm Active on apexhacks.org. If Updating, wait or read refunds policy."
        ]
      }
    ]
  }
]

export function getBlog(slug: string) {
  return BLOGS.find((b) => b.slug === slug)
}

/** Related threads for forum footers — never includes the current slug. */
export function getRelatedForumThreads(slug: string, limit = 6): BlogPost[] {
  const current = getBlog(slug)
  if (!current) return []
  return BLOGS.filter((b) => b.slug !== slug)
    .sort((a, b) => {
      const tagRank = (p: BlogPost) => (p.tag === current.tag ? 0 : 1)
      const byTag = tagRank(a) - tagRank(b)
      if (byTag !== 0) return byTag
      return a.title.localeCompare(b.title)
    })
    .slice(0, limit)
}

export { blogPath } from './blog-paths'
